In [1]:
from keras.datasets import mnist
from keras.utils import np_utils


(X_train, y_train), (X_test, y_test) = mnist.load_data()

X_train = X_train.reshape(X_train.shape[0], -1)/255
X_test = X_test.reshape(X_test.shape[0], -1)/255
y_train = np_utils.to_categorical(y_train, num_classes=10)
y_test = np_utils.to_categorical(y_test, num_classes=10)
print(X_train[1].shape)
print(y_train[:3])

(784,)
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [7]:
import numpy as np
np.random.seed(1337)  # for reproducibility
from keras.datasets import mnist
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import RMSprop

model = Sequential([
    Dense(32, input_dim = 784),
    Activation('relu'),
    Dense('10'),
    Activation('softmax'),
])

rmsprop = RMSprop(lr=0.001, rho=0.9, epsilon=1e-08, decay=0.0)

model.compile(optimizer=rmsprop,
             loss='categorical_crossentropy',
             metrics=['accuracy','crossentropy'])


print('Training-----------')
model.fit(X_train, y_train, epochs=50, batch_size=32)


print('Testing------------')
loss, accuracy, cross = model.evaluate(X_test, y_test)
print('test loss:', loss)
print('test accuracy:', accuracy)
print('test crossentropy:', cross)

Training-----------
Epoch 1/50
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3595 - accuracy: 0.8993 - crossentropy: 0.3595
Epoch 2/50
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2043 - accuracy: 0.9408 - crossentropy: 0.2043
Epoch 3/50
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1639 - accuracy: 0.9524 - crossentropy: 0.1639
Epoch 4/50
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1422 - accuracy: 0.9600 - crossentropy: 0.1422
Epoch 5/50
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1280 - accuracy: 0.9635 - crossentropy: 0.1280
Epoch 6/50
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1179 - accuracy: 0.9664 - crossentropy: 0.1179
Epoch 7/50
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1105 - accuracy: 0.9685 - crossentropy: 0.1105
Epoch 8/50
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1042 - accuracy: 0.9709 - c